package com.techafresh.composeeasyforms

enum class MyFormsKeys {
    EMAIL, PASSWORD, SALUTATION, NAME, URL, CUSTOM_FOCUS,
    PHONE, CARD, CHECKBOX, LIST_CHECKBOX, TRI_CHECKBOX, RADIO_BUTTON,
    SWITCH, SLIDER, RANGE_SLIDER, CUSTOM_PASSWORD
}
